ALTER TABLE topics
DROP
FOREIGN KEY FK_TOPICS_ON_CURSO;

ALTER TABLE topics
    ADD course_id BIGINT NULL;

ALTER TABLE topics
    MODIFY course_id BIGINT NOT NULL;

ALTER TABLE topics
    ADD CONSTRAINT FK_TOPICS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE topics
DROP
COLUMN curso_id;